name: second-action

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  check-bats-version:
    runs-on: 
      group: ubuntu-runners
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  hello_world_job: 
    needs: check-bats-version
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Get the output time
        run: echo "The time was 5 AM"